# https://github.com/andresemartinez/esphome-nodes/tree/main/home-voltage-sensor
# v0.3

esphome:
  name: "home-voltage-sensor"

esp8266:
  board: esp01_1m

logger:
  level: INFO

api:

ota:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

sensor:
    
  # Voltage Sensor
  # Even though ct_clamp platform is intended for current measurement
  # it actually calculates the Vrms based on the configured adc sensor readings.
  # So if connected to a ZMPT101B module it is calculating AC voltage.
  - platform: ct_clamp
    sensor: adc_sensor # ADC to use for measurement
    name: "Home Voltage"
    update_interval: 2s # less than 2s makes the Wi-Fi connection unstable
    filters:
      - calibrate_linear:
        - 0 -> 0
        - 0.029 -> 222
      - or: # publish updates every 10 minutes or when there is a 5v delta
        - throttle: 10min
        - delta: 5.0
        
    # HA metadata
    unit_of_measurement: "V"
    icon: "mdi:current-ac"
    device_class: "voltage"
    state_class: "measurement"
    accuracy_decimals: 0

  # -----------------------------------------------------------------

  # Raw measurements from ZMPT101B module for Voltage Sensor 
  - platform: adc
    pin: A0
    id: adc_sensor
    filters:
      - offset: -1.65 # ZMPT101B module offset (sensor vcc / 2)

    disabled_by_default: true # Do not add this sensor to HA
