# https://github.com/andresemartinez/esphome-nodes/tree/main/home-voltage-sensor
# v0.3

esphome:
  name: "home-voltage-sensor"

esp8266:
  board: esp01_1m

logger:

api:

ota:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

sensor:
  # Voltage Sensor
  - platform: ct_clamp # calculates vrms based on ADC
    sensor: adc_sensor # ADC to use for measurement
    name: "Home Voltage"
    update_interval: 2s # TODO: check if it can be lowered
    filters:
      - calibrate_linear: # calibrate readings (adc reading -> measured voltage)
          - 0 -> 0
          - 0.074 -> 229

      - or: # comment this filter for calibration
          - throttle: 30min
          - delta: 2.0

    # HA metadata
    unit_of_measurement: "V"
    icon: "mdi:current-ac"
    device_class: "voltage"
    state_class: "measurement"
    accuracy_decimals: 2

  - platform: adc
    pin: A0
    id: adc_sensor
    filters:
      - offset: -1.65 # sensor vcc / 2

    disabled_by_default: true # Do not add to HA
